name: my_weather_app_flutter
description: "A Flutter application that shows the current weather and the forecast for the following days."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  location: ^7.0.0
  http: ^1.2.2
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
     - assets/img/
